"use client";
import { DatePicker } from "@/components/ui/date-picker";
import { Select } from "@/components/ui/select";
import { useEffect, useRef, useState } from "react";
import { useParams, useSearchParams } from "next/navigation";
import Link from "next/link";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { axios } from "@/lib/config";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import toast from "react-hot-toast";
import OutcomeInsights from "@/components/custom/OutcomeInsights";

type Json = string | number | boolean | null | Json[] | { [key: string]: Json };
interface Suggestion { field: string; index?: number; current: string; suggested: string; reason: string; confidence: number; evidence: string[] }
interface Item { _id: string; missingInformation?: string[]; targetJob?: string | null; usage?: Record<string, number>; title?: string; company?: string; description?: string; position?: string; status?: string; content?: string; kind?: string; output?: Record<string, Json>; suggestions?: Suggestion[]; questions?: string[]; answers?: { answer: string; feedback: Record<string, Json> }[]; createdAt?: string; resume?: string; job?: string; url?: string; notes?: string; dateApplied?: string; interviewDates?: string[]; coverLetter?: string; analysis?: Record<string, Json>; timeline?: { status: string; date: string }[] }
const tools: Record<string, { title: string; description: string; path: string; requiresJob?: boolean }> = {
  match: { title: "Resume and job match", description: "Compare skills, seniority, experience and responsibilities with supporting evidence.", path: "generate/match", requiresJob: true },
  jobs: { title: "Job analyzer", description: "Understand the requirements before tailoring your resume.", path: "jobs" },
  ats: { title: "Resume match & ATS review", description: "See what matches, what is missing, and how each score is calculated.", path: "ats", requiresJob: true },
  optimizer: { title: "Resume optimizer", description: "Review every suggested change before applying it.", path: "generate/optimizer" },
  bullets: { title: "Achievement bullet writer", description: "Turn your real work into clear, specific statements.", path: "generate/bullets" },
  summary: { title: "Summary writer", description: "Build a summary from your actual experience and skills.", path: "generate/summary" },
  skills: { title: "Skills analyzer", description: "Identify relevant skills. Only add skills you actually possess.", path: "generate/skills" },
  coach: { title: "AI career coach", description: "A conversation grounded in your career profile, resume and target job.", path: "generate/coach" },
  linkedin: { title: "LinkedIn optimizer", description: "Shape a consistent professional story across your profile.", path: "generate/linkedin" },
  gap: { title: "Career gap analysis", description: "Prioritize your next 30, 60 and 90 days. A plan is not a hiring guarantee.", path: "generate/gap" },
  "cover-letters": { title: "Cover letters", description: "Draft a letter from your experience. Add a target job to tailor it to a specific opportunity.", path: "cover-letters" },
  interviews: { title: "Interview coach", description: "Practice one question at a time and get specific feedback.", path: "interviews" },
  applications: { title: "Application tracker", description: "Keep each opportunity and its next steps in one place.", path: "applications" },
};
const statuses = ["Saved", "Applied", "Screening", "Interview", "Technical Interview", "Final Interview", "Offer", "Rejected", "Withdrawn"];
const label = (value: string) => value.replace(/([A-Z])/g, " $1").replace(/[-_]/g, " ").replace(/^./, s => s.toUpperCase());
function Result({ value }: { value: Json }) {
  if (value === null) return <span className="text-muted-foreground">Not enough information</span>;
  if (Array.isArray(value)) return value.length ? <ul className="space-y-2">{value.map((item, i) => <li key={i} className="rounded-lg bg-muted/50 p-3"><Result value={item}/></li>)}</ul> : <span className="text-muted-foreground">None identified</span>;
  if (typeof value === "object") return <dl className="space-y-4">{Object.entries(value).map(([key, item]) => <div key={key}><dt className="mb-1 text-sm font-semibold">{label(key)}</dt><dd><Result value={item}/></dd></div>)}</dl>;
  return <p className="whitespace-pre-wrap break-words text-sm leading-relaxed">{String(value)}</p>;
}
function download(content: string, name: string) {
  const url = URL.createObjectURL(new Blob([content], { type: "text/plain;charset=utf-8" }));
  const anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url);
}
function SuggestionCard({ suggestion, analysisId, index }: { suggestion: Suggestion; analysisId: string; index: number }) {
  const [text, setText] = useState(suggestion.suggested); const [dismissed, setDismissed] = useState(false);
  const client = useQueryClient();
  const apply = useMutation({ mutationFn: () => axios.post(`career/analyses/${analysisId}/apply`, { index, edited: text, confirmed: true }), onSuccess: () => { toast.success("Applied and saved to resume"); setDismissed(true); client.invalidateQueries({ queryKey: ["resume-by-id"] }); }, onError: (error: Error) => toast.error(error.message) });
  if (dismissed) return null;
  return <article className="space-y-3 rounded-xl border p-5"><h3 className="font-semibold">{label(suggestion.field)} · {Math.round(suggestion.confidence * 100)}% model confidence</h3><p className="text-xs font-semibold uppercase text-muted-foreground">Before</p><p className="whitespace-pre-wrap text-sm">{suggestion.current || "Empty"}</p><label className="block text-xs font-semibold uppercase text-muted-foreground">After - edit before applying<Textarea className="mt-2 normal-case font-normal text-foreground" rows={5} value={text} onChange={e => setText(e.target.value)}/></label><p className="text-sm"><strong>Why:</strong> {suggestion.reason}</p><details><summary className="text-sm">Supporting evidence</summary><Result value={suggestion.evidence}/></details><p className="text-xs text-muted-foreground">Apply confirms these statements are accurate for your career.</p><div className="flex gap-2"><Button disabled={apply.isPending || !text.trim()} onClick={() => apply.mutate()}>Apply</Button><Button variant="outline" onClick={() => setDismissed(true)}>Reject</Button></div></article>;
}
export default function CareerTool() {
  const { tool: routeTool } = useParams<{tool: string}>();
  const [coachAction, setCoachAction] = useState("coach");
  const tool = routeTool === "coach" ? coachAction : routeTool;
  const config = tools[tool];
  const activeTool = useRef(tool); activeTool.current = tool;
  const [actionError, setActionError] = useState("");
  const searchParams = useSearchParams();
  const client = useQueryClient();
  useEffect(() => { const id = searchParams.get("resume"); if (id && /^[a-f0-9]{24}$/i.test(id)) setResumeId(id); const job = searchParams.get("job"); if (job && /^[a-f0-9]{24}$/i.test(job)) setJobId(job); }, [searchParams]);
  const [resumeId, setResumeId] = useState(""); const [jobId, setJobId] = useState(""); const [style, setStyle] = useState("professional"); const [message, setMessage] = useState(""); const [targetRole, setTargetRole] = useState("");
  const [result, setResult] = useState<Item>(); const [selected, setSelected] = useState<Item>();
  const [title, setTitle] = useState(""); const [company, setCompany] = useState(""); const [description, setDescription] = useState(""); const [url, setUrl] = useState(""); const [content, setContent] = useState(""); const [answer, setAnswer] = useState("");
  const [paperSize, setPaperSize] = useState("A4");
  const [status, setStatus] = useState("Saved"); const [notes, setNotes] = useState(""); const [dateApplied, setDateApplied] = useState(""); const [interviewDates, setInterviewDates] = useState(""); const [letterId, setLetterId] = useState("");
  const [search, setSearch] = useState(""); const [filter, setFilter] = useState(""); const [sort, setSort] = useState("newest"); const [page, setPage] = useState(1);
  const { data: resumes, isLoading: resumesLoading, isError: resumesError, refetch: reloadResumes } = useQuery({ queryKey: ["career-resumes"], queryFn: async () => (await axios.get("resume/getResumes?limit=100")).data.resumes as Item[] });
  const { data: jobs, isLoading: jobsLoading, isError: jobsError, refetch: reloadJobs } = useQuery({ queryKey: ["career-jobs"], queryFn: async () => (await axios.get("career/jobs")).data.items as Item[] });
  const { data: availability } = useQuery({ queryKey: ["ai-status"], queryFn: async () => (await axios.get("career/ai/status")).data as { enabled: boolean }, staleTime: 30000 });
  const collection = ["jobs", "applications", "cover-letters", "interviews"].includes(tool) ? tool : "analyses";
  const { data: saved, isError, isLoading } = useQuery({ queryKey: ["career-saved", collection, tool, page, search, filter, sort], queryFn: async () => (await axios.get(`career/${collection}`, { params: { page, search, sort, ...(collection === "analyses" ? { kind: tool } : {}), ...(filter ? { status: filter } : {}) } })).data as { items: Item[]; total: number } });
  const { data: history } = useQuery({ queryKey: ["coach-history", resumeId], enabled: routeTool === "coach" && !!resumeId, queryFn: async () => (await axios.get(`career/coach/${resumeId}`)).data.messages as { _id: string; role: string; content: string }[] });
  const { data: letters } = useQuery({ queryKey: ["career-letters"], enabled: tool === "applications", queryFn: async () => (await axios.get("career/cover-letters")).data.items as Item[] });
  useEffect(() => { setResult(undefined); setSelected(undefined); setPage(1); setSearch(""); setFilter(""); setSort("newest"); setTitle(""); setCompany(""); setUrl(""); setDescription(""); setContent(""); setAnswer(""); setActionError(""); }, [tool]);
  const action = useMutation({ mutationFn: async ({ path, payload, method = "post" }: { path: string; payload?: unknown; method?: "post" | "put" | "delete" }) => {
    const requestedTool = tool;
    if (path === "ats") {
      const input = payload as { jobId: string };
      const job = (await axios.get(`career/jobs/${input.jobId}`)).data.item as Item;
      if (!job.analysis) await axios.post(`career/jobs/${input.jobId}/analyze`);
    }
    return { ...(await axios({ method, url: `career/${path}`, data: payload })).data, requestedTool };
  }, onMutate: ({ path }) => {
    setActionError("");
    if (process.env.NODE_ENV === "development") console.debug("[DEBUG-RESUMEXPRESS-UI]", { control: "career-action", tool, operation: path.split("/")[0], hasResume: !!resumeId, hasJob: !!(jobId || resumes?.find(item => item._id === resumeId)?.targetJob) });
    return { requestedTool: tool };
  }, onSuccess: data => {
    client.invalidateQueries({ queryKey: ["career-saved"] }); client.invalidateQueries({ queryKey: ["career-jobs"] }); client.invalidateQueries({ queryKey: ["coach-history"] }); client.invalidateQueries({ queryKey: ["workspace-overview"] });
    if (activeTool.current !== data.requestedTool) return;
    const item = data.analysis ?? data.job ?? data.letter ?? data.session ?? data.application;
    if (item) { setResult(item); if (item.content) { setContent(item.content); setTitle(item.title ?? ""); } if (item.questions) setAnswer(""); }
    if (tool === "applications" && item) setSelected(item);
    if (tool === "jobs" && item) { setTitle(item.title ?? ""); setCompany(item.company ?? ""); setDescription(item.description ?? ""); setUrl(item.url ?? ""); }
    toast.success("Saved");
  }, onError: (error: unknown, _variables, mutationContext) => { if (mutationContext?.requestedTool !== activeTool.current) return; const e = error as { response?: { data?: { message?: string; errors?: { message: string }[] } } }; const message = e.response?.data?.errors?.[0]?.message ?? e.response?.data?.message ?? "Request failed. Please try again."; setActionError(message); toast.error(message); } });
  const linkedAnalysis = searchParams.get("analysis");
  const { data: linkedItem } = useQuery({ queryKey: ["linked-analysis", linkedAnalysis], enabled: !!linkedAnalysis && collection === "analyses", queryFn: async () => (await axios.get(`career/analyses/${linkedAnalysis}`)).data.item as Item });
  useEffect(() => {
    if (linkedItem?.kind === tool) { setResult(linkedItem); setResumeId(linkedItem.resume ?? ""); setJobId(linkedItem.job ?? ""); }
  }, [linkedItem, tool]);
  const pdf = useMutation({ mutationFn: async () => (await axios.get(`career/cover-letters/${result?._id}/pdf`, { params: { paperSize }, responseType: "blob" })).data as Blob, onSuccess: blob => { const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "cover-letter.pdf"; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }, onError: () => toast.error("Could not download PDF. Save the letter and try again.") });
  const importDocument = useMutation({ mutationFn: async (file: File) => {
    if (file.size > 3 * 1024 * 1024) throw new Error("Choose a document smaller than 3 MB.");
    if (/\.(txt|md)$/i.test(file.name)) { const text = await file.text(); if (text.length > 30000) throw new Error("Use at most 30,000 characters."); return text; }
    const content = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(",")[1]); reader.onerror = () => reject(new Error("Could not read the file.")); reader.readAsDataURL(file); });
    return (await axios.post("career/jobs/import", { filename: file.name, content })).data.text as string;
  }, onSuccess: text => { setDescription(text); toast.success("Text imported. Review it before saving."); }, onError: (error: unknown) => { const e = error as { message?: string; response?: { data?: { message?: string } } }; toast.error(e.response?.data?.message ?? e.message ?? "Could not import document."); } });
  if (!config) return <div className="p-8">Tool not found. <Link href="/dashboard">Return to dashboard</Link></div>;
  const selectedResume = resumes?.find(item => item._id === resumeId);
  const effectiveJobId = jobId || selectedResume?.targetJob || "";
  const jobRequired = config.requiresJob === true;
  const blocker = resumesLoading ? "Loading your resumes..." : resumesError ? "Your resumes could not be loaded. Retry below." : !resumeId ? "Choose a resume to use your saved experience." : jobRequired && !effectiveJobId ? "Choose a target job so we can compare its requirements with your resume." : tool !== "ats" && availability?.enabled === false ? "AI generation is unavailable on this server. Your saved work is still available." : "";
  const jobHint = selectedResume?.targetJob ? "Use this resume’s saved target job" : jobRequired ? "Choose a target job" : "No target job - use my experience";
  const context = { resumeId, ...(effectiveJobId ? { jobId: effectiveJobId } : {}), targetRole, style, message };
  const pending = action.isPending;
  const chooseSaved = (item: Item) => {
    setSelected(item); setResult(item);
    setActionError("");
    if (item.resume) setResumeId(item.resume);
    setJobId(item.job ?? "");
    if (tool === "jobs") { setTitle(item.title ?? ""); setCompany(item.company ?? ""); setDescription(item.description ?? ""); setUrl(item.url ?? ""); }
    if (tool === "cover-letters") { setContent(item.content ?? ""); setTitle(item.title ?? ""); }
    if (tool === "interviews") setAnswer("");
    if (tool === "applications") { setTitle(item.position ?? ""); setCompany(item.company ?? ""); setUrl(item.url ?? ""); setStatus(item.status ?? "Saved"); setNotes(item.notes ?? ""); setDateApplied(item.dateApplied ?? ""); setInterviewDates((item.interviewDates ?? []).join(", ")); setResumeId(item.resume ?? ""); setLetterId(item.coverLetter ?? ""); }
  };
  const output = result?.output;
  const suggestions = (output?.suggestions ?? []) as unknown as Suggestion[];
  const scoreKeys = ["overallScore", "keywordMatch", "skillsMatch", "experienceRelevance", "achievementStrength", "readability", "formatting"];
  return <div className="mx-auto max-w-7xl px-4 py-8 sm:px-8">
    <header className="mb-8"><p className="mb-2 text-xs font-semibold uppercase tracking-widest text-muted-foreground">Career workspace</p><h1 className="text-3xl font-semibold tracking-tight">{routeTool === "coach" ? "AI career copilot" : config.title}</h1><p className="mt-2 max-w-2xl text-muted-foreground">{config.description}</p></header>
    {routeTool === "applications" && <div className="mb-6"><OutcomeInsights /></div>}
    {routeTool === "coach" && <section className="mb-6 space-y-3 rounded-xl border border-primary/20 bg-primary/5 p-5"><label className="block text-sm font-medium">What would you like help with?<Select className="mt-2 block w-full rounded border bg-card p-2" value={coachAction} disabled={pending} onValueChange={value => setCoachAction(value)} aria-label="What would you like help with?" options={["coach", "summary", "bullets", "skills", "ats", "match", "optimizer", "cover-letters", "interviews", "linkedin", "gap"].map(value => ({ value, label: tools[value].title }))}/></label><p className="text-sm">Your selected resume, target job and notes stay with you when switching actions. Review suggested edits before applying them.</p>{resumeId && <Link className="inline-block text-sm font-medium text-primary underline" href={`/dashboard/resume/${resumeId}/edit#resume-ai`}>Draft or edit the full resume</Link>}</section>}
    <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_300px]"><div className="min-w-0 space-y-6">
      <fieldset disabled={pending} className="min-w-0 space-y-4 rounded-xl border bg-card p-5 sm:p-6">
        {tool === "jobs" ? <><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Job title<Input maxLength={200} value={title} onChange={e => setTitle(e.target.value)}/></label><label className="text-sm">Company<Input maxLength={200} value={company} onChange={e => setCompany(e.target.value)}/></label></div><label className="block text-sm">Job URL<Input type="url" value={url} onChange={e => setUrl(e.target.value)}/></label><label className="block text-sm">Job description<Textarea maxLength={30000} rows={12} value={description} onChange={e => setDescription(e.target.value)}/></label><label className="block text-sm">Import a document (PDF, Word, TXT or Markdown)<input className="mt-2 block max-w-full text-sm" type="file" accept=".pdf,.docx,.txt,.md" disabled={importDocument.isPending} onChange={e => { const file = e.target.files?.[0]; if (file) importDocument.mutate(file); e.target.value = ""; }}/></label>{importDocument.isPending && <p role="status" className="text-sm">Reading document...</p>}<p className="text-xs text-muted-foreground">Maximum 3 MB. PDFs must contain selectable text. Review the imported text before saving.</p>{(!title.trim() || description.trim().length < 80) && <p className="text-sm text-muted-foreground">{!title.trim() ? "Add a job title. " : ""}{description.trim().length < 80 ? `Add at least 80 characters of job description (${description.trim().length}/80).` : ""}</p>}<Button disabled={pending || importDocument.isPending || !title.trim() || description.trim().length < 80} onClick={() => action.mutate({ path: "jobs", payload: { title: title.trim(), company: company.trim(), description: description.trim(), url: url.trim() } })}>{pending ? "Saving..." : "Save job description"}</Button></> : <>
          <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Resume{tool === "applications" ? " (optional)" : " (required)"}<Select disabled={resumesLoading || resumesError} className="mt-1 block w-full rounded border p-2" value={resumeId} onValueChange={value => { setResumeId(value); if (tool !== "applications") { setResult(undefined); setSelected(undefined); } setActionError(""); }} aria-label="Resume" options={[{ value: "", label: resumesLoading ? "Loading resumes..." : resumesError ? "Could not load resumes" : "Choose a resume" }, ...(resumes?.map(item => ({ value: item._id, label: item.title || "Untitled resume" })) ?? [])]}/></label>{tool !== "applications" && <label className="text-sm">Target job {jobRequired ? "(required)" : "(optional)"}<Select disabled={jobsLoading || jobsError} className="mt-1 block w-full rounded border p-2" value={jobId} onValueChange={value => { setJobId(value); setActionError(""); }} aria-label="Target job" options={[{ value: "", label: jobsLoading ? "Loading jobs..." : jobsError ? "Could not load jobs" : jobHint }, ...(jobs?.map(item => ({ value: item._id, label: `${item.title} · ${item.company}` })) ?? [])]}/></label>}</div>
          {resumesError && <p role="alert" className="text-sm text-red-300">Could not load resumes. <button type="button" className="underline underline-offset-4" onClick={() => reloadResumes()}>Retry</button></p>}
          {!resumesLoading && !resumesError && !resumes?.length && <p className="text-sm text-muted-foreground">No resumes yet. <Link className="text-primary underline underline-offset-4" href="/dashboard/ai">Create your first resume with AI</Link></p>}
          {tool !== "applications" && <div className="flex flex-wrap items-center justify-between gap-2 text-xs text-muted-foreground">{jobsError ? <p role="alert">Could not load target jobs. <button type="button" className="text-primary underline" onClick={() => reloadJobs()}>Retry</button></p> : <p>{effectiveJobId ? "Your selected job will guide this result." : jobRequired ? "A job description is needed for a meaningful comparison." : "A target job is optional. We’ll use your resume and target role."}</p>}<Link className="text-primary underline underline-offset-4" href={`/dashboard/career/jobs${resumeId ? `?resume=${resumeId}` : ""}`}>Add or manage target jobs</Link></div>}
          {tool === "applications" ? <><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Position<Input maxLength={200} value={title} onChange={e => setTitle(e.target.value)}/></label><label className="text-sm">Company<Input maxLength={200} value={company} onChange={e => setCompany(e.target.value)}/></label><label className="text-sm">Job URL<Input value={url} onChange={e => setUrl(e.target.value)}/></label><label className="text-sm">Date applied<DatePicker aria-label="Date applied" value={dateApplied} onValueChange={setDateApplied}/></label><label className="text-sm">Status<Select className="mt-1 block w-full rounded border p-2" value={status} onValueChange={value => setStatus(value)} aria-label="Status" options={statuses.map(value => ({ value, label: value }))}/></label><label className="text-sm">Cover letter<Select className="mt-1 block w-full rounded border p-2" value={letterId} onValueChange={value => setLetterId(value)} aria-label="Cover letter" options={[{ value: "", label: "None" }, ...(letters?.map(item => ({ value: item._id, label: item.title || "Untitled cover letter" })) ?? [])]}/></label></div><label className="block text-sm">Interview dates (comma separated)<Input value={interviewDates} onChange={e => setInterviewDates(e.target.value)}/></label><label className="block text-sm">Notes<Textarea maxLength={10000} value={notes} onChange={e => setNotes(e.target.value)}/></label>{(!title.trim() || !company.trim()) && <p className="text-sm text-muted-foreground">Add a position and company to save this application. Resume and cover letter are optional.</p>}<div className="flex gap-2"><Button disabled={pending || !title.trim() || !company.trim()} onClick={() => action.mutate({ path: `applications${selected ? `/${selected._id}` : ""}`, method: selected ? "put" : "post", payload: { company, position: title, url, status, notes, dateApplied, interviewDates: interviewDates.split(",").map(s => s.trim()).filter(Boolean), ...(resumeId ? { resume: resumeId } : {}), ...(letterId ? { coverLetter: letterId } : {}) } })}>{selected ? "Update application" : "Save application"}</Button>{selected && <Button variant="outline" onClick={() => { setSelected(undefined); setResult(undefined); setTitle(""); setCompany(""); setUrl(""); setStatus("Saved"); setNotes(""); setDateApplied(""); setInterviewDates(""); setResumeId(""); setLetterId(""); }}>New application</Button>}</div></> : <>
            {tool !== "ats" && <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Target role<Input maxLength={200} value={targetRole} onChange={e => setTargetRole(e.target.value)}/></label><label className="text-sm">Style<Select className="mt-1 block w-full rounded border p-2" value={style} onValueChange={value => setStyle(value)} aria-label="Style" options={["professional", "technical", "executive", "concise", "achievement-focused", "standard"].map(value => ({ value, label: value.charAt(0).toUpperCase() + value.slice(1) }))}/></label></div>}
            {!["ats", "interviews"].includes(tool) && <label className="block text-sm">{tool === "coach" ? "Your message" : "Additional confirmed facts or instructions"}<Textarea maxLength={30000} rows={4} value={message} onChange={e => setMessage(e.target.value)}/></label>}
            {blocker && <p id="career-action-help" role="status" className="rounded-lg border border-primary/20 bg-primary/5 px-3 py-2 text-sm">{blocker}</p>}
            <Button disabled={pending || !!blocker} aria-describedby={blocker ? "career-action-help" : undefined} onClick={() => action.mutate({ path: config.path, payload: context })}>{pending ? (tool === "ats" ? "Checking job requirements and resume..." : "Working...") : tool === "interviews" ? "Start practice interview" : tool === "coach" ? "Send message" : tool === "ats" ? "Analyze match" : "Generate"}</Button><p className="text-xs text-muted-foreground">AI drafts use your saved resume and career profile. Verify every claim before using it.</p>
          </>}
        </>}
      </fieldset>
      {actionError && <p role="alert" className="rounded-xl border border-red-400/30 bg-red-400/5 p-4 text-sm text-red-300">{actionError}</p>}
      {tool === "coach" && history?.map(item => <article key={item._id} className={`rounded-xl border p-5 ${item.role === "user" ? "bg-muted/50" : "bg-card"}`}><p className="mb-2 text-xs font-semibold uppercase text-muted-foreground">{item.role === "user" ? "You" : "Career coach"}</p><p className="whitespace-pre-wrap text-sm leading-relaxed">{item.content}</p></article>)}
      {result && <fieldset disabled={pending} className="min-w-0 space-y-5 rounded-xl border bg-card p-5 sm:p-6">
        {result.usage && <details className="text-xs text-muted-foreground"><summary>AI token usage</summary><p>Input: {result.usage.promptTokenCount ?? "Unavailable"} · Output: {result.usage.candidatesTokenCount ?? "Unavailable"} · Total: {result.usage.totalTokenCount ?? "Unavailable"}</p><p>Provider-reported tokens for this saved generation, including validation retries when reported. Cached results reuse the original record. These counts are not a billing estimate.</p></details>}
        {tool === "jobs" && <><h2 className="text-xl font-semibold">{result.title} · {result.company}</h2><Button disabled={pending} onClick={() => action.mutate({ path: `jobs/${result._id}/analyze` })}>{pending ? "Analyzing..." : "Analyze requirements"}</Button>{result.analysis ? <Result value={result.analysis}/> : <p className="whitespace-pre-wrap text-sm">{result.description}</p>}<Link className="block underline" href={`/dashboard/career/ats?job=${result._id}${resumeId ? `&resume=${resumeId}` : ""}`}>Match a resume to this job</Link></>}
        {tool === "ats" && output && <><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{scoreKeys.map(key => <details key={key} className="rounded-xl border p-4"><summary className="cursor-pointer text-sm">{label(key)}<span className="mt-2 block text-3xl font-semibold">{output[key] === null ? "N/A" : `${output[key] ?? 0}%`}</span></summary><p className="mt-3 text-xs text-muted-foreground">{String((output.explanations as Record<string, Json>)?.[key] ?? "")}</p></details>)}</div><p className="text-xs text-muted-foreground">Diagnostic heuristics, not an employer ATS score or hiring prediction. Open each score for its calculation.</p><Result value={Object.fromEntries(Object.entries(output).filter(([key]) => !scoreKeys.includes(key) && !["explanations", "atsCompatibility"].includes(key)))}/></>}
        {suggestions.map((suggestion, index) => <SuggestionCard key={`${result._id}-${index}`} suggestion={suggestion} analysisId={result._id} index={index}/>)}
        {output?.questions && tool !== "coach" && <Result value={{ questions: output.questions }}/>}
        {output && !["ats", "coach"].includes(tool) && !output.suggestions && <><Result value={output}/><Button variant="outline" onClick={() => download(Object.entries(output).map(([key, value]) => `${label(key)}\n${typeof value === "string" ? value : JSON.stringify(value, null, 2)}`).join("\n\n"), `${tool}.txt`)}>Download results</Button></>}
        {tool === "cover-letters" && <>{!!result.missingInformation?.length && <div className="rounded-lg border border-primary/20 bg-primary/5 p-3 text-sm"><p className="font-medium">Details that would strengthen this letter</p><ul className="mt-2 list-disc space-y-1 pl-5">{result.missingInformation.map((item, i) => <li key={i}>{item}</li>)}</ul></div>}{(!title.trim() || !content.trim()) && <p className="text-sm text-muted-foreground">Add a title and letter content before saving.</p>}<label className="block text-sm">Title<Input maxLength={300} value={title} onChange={e => setTitle(e.target.value)}/></label><label className="block text-sm">Letter<Textarea maxLength={20000} rows={18} value={content} onChange={e => setContent(e.target.value)}/></label><div className="flex flex-wrap gap-2"><Button disabled={pending || !title.trim() || !content.trim()} onClick={() => action.mutate({ path: `cover-letters/${result._id}`, method: "put", payload: { title, content } })}>Save edits</Button><Button variant="outline" onClick={async () => { try { await navigator.clipboard.writeText(content); toast.success("Copied"); } catch { toast.error("Could not copy. Select and copy the text."); } }}>Copy</Button><Button variant="outline" onClick={() => download(content, "cover-letter.txt")}>Download text</Button><label className="text-sm">PDF paper<Select className="ml-2 rounded border p-2" value={paperSize} onValueChange={value => setPaperSize(value)} aria-label="PDF paper" options={["A4", "Letter"].map(value => ({ value, label: value }))}/></label><Button variant="outline" disabled={pdf.isPending || pending || content !== result.content || title !== result.title} onClick={() => pdf.mutate()}>{pdf.isPending ? "Preparing PDF..." : "Download saved PDF"}</Button></div>{(content !== result.content || title !== result.title) && <p className="text-xs text-muted-foreground">Save your edits before downloading the PDF.</p>}</>}
        {tool === "interviews" && result.questions && <><p className="text-sm text-muted-foreground">Question {Math.min((result.answers?.length ?? 0) + 1, result.questions.length)} of {result.questions.length}</p>{result.status !== "complete" ? <><h2 className="text-lg font-semibold">{result.questions[result.answers?.length ?? 0]}</h2><label className="block text-sm">Your answer<Textarea maxLength={10000} rows={7} value={answer} onChange={e => setAnswer(e.target.value)}/></label><Button disabled={pending || !answer.trim()} onClick={() => action.mutate({ path: `interviews/${result._id}/answer`, payload: { answer } })}>Evaluate answer & continue</Button></> : <h2 className="text-lg font-semibold">Practice complete · {Math.round((result.answers ?? []).reduce((total, entry) => total + Number(entry.feedback.relevance ?? 0) + Number(entry.feedback.clarity ?? 0) + Number(entry.feedback.structure ?? 0), 0) / ((result.answers?.length ?? 1) * 3))}% average relevance, clarity and structure</h2>}{result.answers?.map((entry, i) => <details key={i} open={i === (result.answers?.length ?? 0) - 1}><summary className="font-medium">Feedback for question {i + 1}</summary><p className="my-3 whitespace-pre-wrap text-sm">{entry.answer}</p><Result value={entry.feedback}/></details>)}</>}
        {tool === "applications" && <><h2 className="font-semibold">Application timeline</h2>{result.timeline?.map((entry, i) => <p key={i} className="border-l-2 py-2 pl-4 text-sm">{entry.status} · {new Date(entry.date).toLocaleString()}</p>)}</>}
      </fieldset>}
    </div><aside className="space-y-4 rounded-xl border bg-muted/50 p-5"><h2 className="font-semibold">Saved {label(collection)}</h2><Input aria-label="Search saved items" value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} placeholder="Search"/><Select aria-label="Sort saved items" className="w-full rounded border p-2 text-sm" value={sort} onValueChange={value => { setSort(value); setPage(1); }} options={["newest", "oldest", "updated", ...(tool === "applications" ? ["status"] : []), ...(["ats", "match"].includes(tool) ? ["score"] : [])].map(value => ({ value, label: ({ newest: "Newest first", oldest: "Oldest first", updated: "Recently edited", status: "Application status", score: "Highest score" } as Record<string, string>)[value] }))}/>{tool === "applications" && <Select aria-label="Filter status" className="w-full rounded border p-2 text-sm" value={filter} onValueChange={value => { setFilter(value); setPage(1); }} options={[{ value: "", label: "All statuses" }, ...statuses.map(value => ({ value, label: value }))]}/>}{isError ? <p role="alert">Could not load saved items.</p> : isLoading ? <p role="status">Loading...</p> : !saved?.items.length ? <p className="text-sm text-muted-foreground">Your saved work will appear here.</p> : saved.items.filter(item => collection !== "analyses" || item.kind === tool).map(item => <button key={item._id} className="block w-full rounded-lg border bg-card p-3 text-left text-sm hover:border-slate-500" disabled={pending} onClick={() => chooseSaved(item)}><span className="block font-medium">{item.title ?? item.position ?? label(item.kind ?? "Interview")}</span><span className="text-xs text-muted-foreground">{item.company ?? item.status ?? (item.createdAt ? new Date(item.createdAt).toLocaleDateString() : "")}</span></button>)}<div className="flex justify-between gap-2"><Button size="sm" variant="outline" disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</Button><Button size="sm" variant="outline" disabled={page * 20 >= (saved?.total ?? 0)} onClick={() => setPage(page + 1)}>Next</Button></div></aside></div>
  </div>;
}
