import Link from "next/link";
import { ArrowRight, ArrowUpRight, Check, FileText, Fingerprint, Orbit, ScanSearch, ShieldCheck, Sparkles, Layers, Download, MessageCircle } from "lucide-react";
const steps = [
  { icon: Fingerprint, n: "01", title: "Bring your experience", text: "Upload a resume or share rough notes. Keep a reusable profile of your real skills, work and education." },
  { icon: ScanSearch, n: "02", title: "Make it relevant", text: "Add a target job. See what matches, what is missing, and which changes are worth making." },
  { icon: Sparkles, n: "03", title: "Make it yours", text: "Review the before and after. Edit the AI draft, approve your changes, and export a polished PDF." },
];
export default function Home() {
  return <div className="landing"><section className="hero-stage"><div className="hero-orbit" aria-hidden="true"/><div className="mx-auto grid max-w-7xl items-center gap-14 px-6 py-20 lg:grid-cols-[1.1fr_1fr] lg:py-28"><div className="relative z-10 animate-enter"><span className="signal-pill"><span/>YOUR CAREER HAS A NEXT CHAPTER</span><h1 className="hero-title">You bring<br/>the ambition.<br/><span className="text-primary">We shape the story.</span></h1><p className="mt-7 max-w-lg text-lg leading-relaxed text-muted-foreground">Turn your experience into a resume built for your next move. AI writing, job insights and polished documents, in one connected workspace.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/auth/signup" className="rx-button">Build my resume<ArrowUpRight size={19}/></Link><Link href="#workflow" className="rx-button secondary">See how it works<ArrowRight size={18}/></Link></div><p className="mt-6 flex items-center gap-2 text-xs text-muted-foreground"><ShieldCheck size={15} className="text-primary"/>Your facts stay yours. You approve every AI edit.</p></div>
    <div className="product-constellation animate-enter" aria-label="Illustrated example of the resume workflow"><div className="floating-label"><Orbit size={16}/><span>A WORKSPACE FOR YOUR NEXT MOVE</span></div><div className="showcase-window"><div className="window-top"><span className="flex gap-1.5"><i/><i/><i/></span><span>Example workflow</span><Layers size={14}/></div><div className="showcase-body"><div className="showcase-rail"><FileText size={18}/><Sparkles size={18} className="text-primary"/><ScanSearch size={18}/></div><div className="showcase-paper"><div className="mb-5 flex items-start justify-between"><div><p className="text-[10px] tracking-widest text-slate-500">SOFTWARE DEVELOPER</p><h2 className="mt-2 text-2xl font-semibold text-slate-900">Alex Example</h2></div><div className="h-8 w-8 rounded-full border-2 border-teal-700"/></div><div className="paper-rule"/><h3>PROFILE</h3><p>Software developer with experience building web applications using React and Node.js.</p><h3>EXPERIENCE</h3><div className="paper-line w-3/4"/><div className="paper-line"/><div className="paper-line w-5/6"/><h3>SKILLS</h3><div className="flex gap-2 text-[10px]"><span className="rounded bg-slate-100 px-2 py-1">React</span><span className="rounded bg-slate-100 px-2 py-1">Node.js</span></div></div></div></div><div className="ai-note"><span className="ai-note-icon"><Sparkles size={19}/></span><div><p className="text-sm font-semibold">A stronger story. Still yours.</p><p className="mt-1 text-xs text-muted-foreground">Review the wording. Keep control of the facts.</p></div></div><div className="export-note"><Check size={15} className="text-primary"/><span>Review → approve → export</span></div></div></div></section>
    <section className="border-y bg-card/50"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-6 px-6 py-7 md:grid-cols-4">{[[Fingerprint,"Reusable career facts"],[ScanSearch,"Job-specific insights"],[Layers,"Version history"],[Download,"Ready-to-send PDFs"]].map(([Icon,title])=> {const I=Icon as typeof Fingerprint;return <div key={String(title)} className="flex items-center gap-3 text-sm text-muted-foreground"><I className="text-primary" size={18}/>{String(title)}</div>;})}</div></section>
    <section id="workflow" className="landing-section"><div className="mb-12 flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">LESS STARTING OVER. MORE MOVING FORWARD.</p><h2 className="section-title">From rough notes<br/>to your next opportunity.</h2></div><p className="max-w-sm text-sm leading-relaxed text-muted-foreground">No blank-page anxiety. No jumping between documents. Just a clear next step.</p></div><div className="grid gap-5 md:grid-cols-3">{steps.map(({icon:Icon,n,title,text})=><article className="feature-card" key={n}><div className="flex items-center justify-between"><span className="feature-icon"><Icon size={23}/></span><span className="text-sm text-muted-foreground">/{n}</span></div><h3 className="mt-10 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{text}</p></article>)}</div></section>
    <section id="why-resumexpress" className="landing-section pt-0"><div className="value-panel"><div><p className="eyebrow">MORE THAN A CONVERSATION</p><h2 className="section-title">A great answer is a start.<br/><span className="text-primary">A finished application<br/>is the goal.</span></h2><p className="mt-6 max-w-md text-sm leading-7 text-muted-foreground">ResumeXpress connects the work around the writing: your career profile, target jobs, approved changes, document layout and application progress.</p><Link href="/auth/signup" className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-primary">Build in one place<ArrowRight size={17}/></Link></div><div className="space-y-4">{[[Fingerprint,"Tell your story once","Reuse your career facts across resumes, cover letters and interview practice."],[ShieldCheck,"See exactly what changes","Compare before and after, edit proposals, and keep a history you can restore."],[FileText,"Leave with a document","Choose a template, check the layout and export a selectable-text PDF."],[MessageCircle,"Keep the next step connected","Practice interviews and track applications alongside the resume you used."]].map(([Icon,title,text])=>{const I=Icon as typeof Fingerprint;return <div className="flex gap-4 rounded-xl border bg-background/50 p-5" key={String(title)}><I className="mt-1 shrink-0 text-primary" size={20}/><div><h3 className="font-medium">{String(title)}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{String(text)}</p></div></div>;})}</div></div></section>
    <section id="questions" className="landing-section pt-0"><p className="eyebrow">BEFORE YOUR NEXT MOVE</p><h2 className="section-title mb-8">A few good questions.</h2><div className="max-w-3xl">{[["Do I need to write everything myself?","No. Start with rough notes, a PDF, a Word document, or your saved career profile. AI can organize and draft the content. You supply missing facts and approve the wording."],["Does AI add experience I don't have?","The assistant is instructed to use your supplied facts and ask about missing information. Drafts include supporting evidence, but you should still review every claim before applying it."],["Can I tailor a resume for different jobs?","Yes. Save jobs, compare their requirements, and create separate resume versions. Your reusable career profile stays available for the next application."],["Will this guarantee an interview?","No. ATS reviews are explainable diagnostics, not an employer's score or a promise of an interview. Use them to make informed improvements."]].map(([question,answer])=><details className="faq-item" key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></section>
    <section className="landing-section pt-0"><div className="final-cta"><Orbit className="mx-auto mb-6 text-primary" size={37}/><h2 className="section-title">Your experience deserves<br/>a better first impression.</h2><Link href="/auth/signup" className="rx-button mt-8">Start your next chapter<ArrowUpRight size={18}/></Link></div></section>
  </div>;
}
