"use client";
import { Select } from "@/components/ui/select";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import Link from "next/link";
import { Sparkles, ArrowUpRight, Fingerprint, ScanSearch, MessageCircle, FileText, Layers, CheckCheck } from "lucide-react";
import { axios } from "@/lib/config";
import NewResumeDialog from "@/components/custom/Dashboard/NewResumeDialog";
const groups = [
  { title:"Write & refine", icon:FileText, tools:[["summary","Professional summary"],["bullets","Experience bullets"],["cover-letters","Cover letter"],["linkedin","LinkedIn profile"]] },
  { title:"Match & improve", icon:ScanSearch, tools:[["optimizer","Tailor to a job"],["ats","ATS review"],["match","Job match"],["skills","Skills analysis"]] },
  { title:"Prepare & progress", icon:MessageCircle, tools:[["coach","Career copilot"],["interviews","Interview practice"],["gap","30 / 60 / 90-day plan"]] },
];
export default function AIAssistantPage() {
  const [resumeId,setResumeId]=useState("");
  const {data:resumes,isLoading,isError}=useQuery({queryKey:["career-resumes"],queryFn:async()=>(await axios.get("resume/getResumes?limit=100")).data.resumes as {_id:string;title:string}[]});
  const {data:ai}=useQuery({queryKey:["ai-status"],queryFn:async()=>(await axios.get("career/ai/status")).data as {enabled:boolean},staleTime:30000});
  const suffix=resumeId?`?resume=${resumeId}`:"";
  return <div className="mx-auto max-w-6xl px-5 py-9 sm:px-8"><header className="mb-8"><p className="eyebrow">IDEAS IN. YOUR NEXT CHAPTER OUT.</p><h1 className="mt-3 text-4xl font-medium">The AI studio.</h1><p className="mt-3 text-sm text-muted-foreground">You don’t need the perfect words. Just the real experience.</p></header>
    {ai?.enabled===false&&<p role="status" className="mb-5 rounded-xl border border-amber-700/40 bg-amber-950/40 p-4 text-sm text-amber-200">AI is not connected on this server yet. You can prepare your profile and import a resume while it is being connected.</p>}
    <section className="studio-start"><div><span className="feature-icon"><Sparkles size={24}/></span><h2 className="mt-6 text-3xl font-medium tracking-tight">Let’s build your story.</h2><p className="mt-3 max-w-md text-sm leading-7 text-muted-foreground">Upload your resume, paste rough notes or use your career profile. Get a draft you can edit, approve and see on the page.</p><div className="mt-7"><NewResumeDialog compact quickStart/></div><p className="mt-3 text-xs text-muted-foreground">Start a fresh draft. Rename it whenever you like.</p></div><div className="studio-sequence">{[{icon:Fingerprint,title:'Start with your facts',text:'Notes, a document, or your saved profile'},{icon:Sparkles,title:'AI shapes the first draft',text:'Clear wording grounded in your experience'},{icon:CheckCheck,title:'You make the final call',text:'Review, edit, approve, then export'}].map(({icon:Icon,title,text},i)=><div key={title} className="flex items-start gap-4"><div className="studio-sequence-icon"><Icon size={20}/>{i<2&&<span/>}</div><div className="pb-7"><h3 className="text-sm font-semibold">{title}</h3><p className="mt-2 text-xs leading-6 text-muted-foreground">{text}</p></div></div>)}</div></section>
    <section className="my-6 flex flex-wrap items-center gap-5 rounded-xl border bg-card p-5"><Layers className="text-primary" size={22}/><div className="min-w-0 flex-1"><label className="text-sm font-medium" htmlFor="studio-resume">Continue with an existing resume</label>{isError?<p role="alert" className="mt-2 text-sm text-red-400">Could not load your resumes. Refresh to try again.</p>:isLoading?<p role="status" className="mt-2 text-xs text-muted-foreground">Loading your workspace...</p>:<Select id="studio-resume" className="mt-2 w-full rounded-lg border px-3 py-2 text-sm" value={resumeId} onValueChange={value =>setResumeId(value)} options={[{ value: "", label: resumes?.length ? "Choose a resume" : "Your first resume will appear here" }, ...(resumes?.map(resume => ({ value: resume._id, label: resume.title })) ?? [])]}/>}</div>{resumeId&&<Link className="rx-button secondary" href={`/dashboard/resume/${resumeId}/edit#resume-ai`}>Continue draft<ArrowUpRight size={16}/></Link>}</section>
    <div className="mb-6 mt-12 flex items-end justify-between gap-4"><div><p className="eyebrow">ONE WORKSPACE. EVERY NEXT STEP.</p><h2 className="mt-2 text-xl font-semibold">Choose your focus.</h2></div><p className="hidden text-xs text-muted-foreground sm:block">{resumeId?'Using your selected resume':'Select a resume inside any tool'}</p></div><div className="grid gap-4 lg:grid-cols-3">{groups.map(({title,icon:Icon,tools})=><section key={title} className="rounded-xl border bg-card p-5"><div className="mb-5 flex items-center gap-3"><Icon size={19} className="text-primary"/><h3 className="text-sm font-semibold">{title}</h3></div><div className="space-y-1">{tools.map(([path,name])=><Link className="group flex items-center justify-between gap-4 rounded-lg px-3 py-3 text-sm text-muted-foreground transition-colors hover:bg-primary/5 hover:text-primary" key={path} href={`/dashboard/career/${path}${suffix}`}>{name}<ArrowUpRight size={15} className="opacity-50 group-hover:opacity-100"/></Link>)}</div></section>)}</div>
    <Link href={`/dashboard/career/coach${suffix}`} className="mt-7 flex flex-wrap items-center gap-4 rounded-xl border border-primary/20 bg-primary/5 p-5"><MessageCircle size={22} className="text-primary"/><div className="flex-1"><h2 className="text-sm font-semibold">Not sure where to start?</h2><p className="mt-1 text-xs leading-6 text-muted-foreground">Your career copilot can explain what’s missing and help you choose the next step.</p></div><ArrowUpRight size={18} className="text-primary"/></Link>
  </div>;
}
